[package]
name = "vibeio-http-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
vibeio-http = { path = "..", features = ["h2"] }

[[bin]]
name = "hpack_decode"
path = "fuzz_targets/hpack_decode.rs"
test = false
doc = false
